### ISSUE TITLE
Discuss MetricsSource parameters

### ISSUE THREAD

**Issue by m-kotowski** [IBMStreams/streamsx.metrics#1]
The first approach for the operator parameters was:

- **connectionURL**: Specifies the connection URL as returned by the `streamtool getjmxconnect` command.
- **user**: Specifies the user that is required for the JMX connection.
- **password**: Specifies the password that is required for the JMX connection.
- **domain**: Specifies the domain that is monitored.
- **retryPeriod**: Specifies the period after which a failed JMX connect is retried. The default is 10.0 seconds.
- **retryCount**: Specifies the retry count for failed JMX connects. The default is -1, which means infinite retries.
- **filterDocument**: Specifies the path to a JSON-formatted document that specifies the domain, instance, job, operator, and metric name filters as regular expressions. Each regular expression must follow the rules that are specified for Java [Pattern](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html).
- **scanPeriod**: Specifies the period after which a new metrics scan is initiated. The default is 5.0 seconds.

Following questions have to be discussed:

- Similar to many other operators the **user** and **password** parameters would be specified as plain text. Shall the operator be prepared to (a) receive password changes on a control port, (b) receive notifications from the some kind of configuration plane?  Or, can we assume that this password is stable forever? Or, is there another mechanism that we can use to get rid of the two parameters?
- Is it possible that JMX provides a list of available domains without the need to know the **domain**?
- Does it make sense to have the **retryPeriod** and **retryCount** parameters, or should the operator retry always? A use case might be that the MetricsSource-using application runs on domain A but monitors domain B, which might be down for whatever reason. Do we want that the application on domain A fails?
- Similar to many other operators, the **scanPeriod** is a pause between two scan cycles. Shall the parameter be renamed to **scanPause**?
- The **filterDocument** parameter will be discussed in another issue. See issue #4 for details.

**Comment by ddebrunner** [comment]
Why not use application configurations instead of user/password/connectionURL?

Would be nice if monitoring the same instance/domain then no configuraiton needs to be provided. E.g. how would I run this on Bluemix?

**Comment by m-kotowski** [comment]
@markheger If needed, please raise the mentioned feature requests.

Connection URL, user, password, and also the filterDocument (as JSON string) can be passed to the operator via an application configuration object. See issue #24 for details.

retryPeriod and retryCount are removed until issue #5 is implemented.

The default domain is the one, under which the MetricsSource operator runs. But, JMX is neither able to provide a list of available domains, nor to provide its own name (related to the JMX connection URL). A feature request should be raised.

Furthermore, there is no official API to retrieve the JMX connection URL via an API that is always available except for streamtool. A feature request should be raised.

So far, we keep scanPeriod as parameter name.
