### ISSUE TITLE
Support Metrics Sinks for integration with popular metrics tools like grafana and kibana

### ISSUE THREAD

**Issue by mikespicer** [IBMStreams/streamsx.metrics#10]
Grafana and Kibana support a variety of stores including elastic search and prometheus so we may choose to provide operators for the stores and to format the data appropriately and composites that use a combination of these for kibanaElasticSerach or grafanaPrometheus etc.

**Comment by m-kotowski** [comment]
According to the discussion of pull request #22, the Grafana and ElasticSearch sink operators are generic enough to develop them in their own repositories. I asked @nelsonong to request separated toolkits. According to him, there is no need to implement composite operators that encapsulate/hide these generic sinks. As soon as these toolkits and the corresponding examples exist, we can close this issue.
