### ISSUE TITLE
MetricsSource shall send tuples even if a metric value did not change

### ISSUE THREAD

**Issue by m-kotowski** [IBMStreams/streamsx.metrics#11]
The current implementation of the MetricsSource operator sends tuples only if a metric value is changed.

For certain use cases, it might be required to get a metric value periodically even if the value did not change.

Either completely remove this feature from the operator and implement it as, for example, composite operator that is also available in this toolkit, or let the application developer decide whether this feature is enabled or disabled (via parameter).

To not duplicate functions, the recommendation is to remove the feature from this operator.

**Comment by ddebrunner** [comment]
I would expect the normal use would be to only send the metric if it has changed. That seems like a useful feature, especially when there are many metrics and only a handful changing.

Maybe a parameter or different operator that provides periodic updates.

**Comment by m-kotowski** [comment]
@ddebrunner Please vote for one of these options and, if needed, propose better names.

**Option 1**: Introduce **emitMetricTuple** parameter

The parameter has the **always** and **onChangedValue** value. The **always** value means that for each selected metric a tuple is emitted during each scan/snapshot cycle. The **onChangedValue** value means that a tuple is emitted only if the metric value changed. The default is **onChangedValue**.

**Option 2**: Introduce **requiredDelta** parameter

The parameter value must be 0, or any positive int64 value. It specifies the minimum delta (abs()) value that must be seen for a metric value before a tuple with the changed value is emitted. 0 is identical to the above mentioned **always** mode, 1 is identical to the above mentioned **onChangedValue** mode. The default is 1.

**Option 3**: Introduce **DeltaMetricsSource** composite

The MetricsSource operator is implemented as if only the **always** mode is implemented. The delta or on-change logic is implemented in a Composite operator that uses the MetricsSource operator and adds a downstream Custom operator.

**Pros/Cons**

Option 2 is an extension of option 1.

Option 3 has the advantage that the MetricsSource operator is simpler and in case that the **always** mode is required, faster because the operator does not need to distinguish between the mode during run-time.

**Comment by ddebrunner** [comment]
Option 3 doesn't have the advantage of being faster in always mode. One can always create an operator that does always or delta without any runtime checks, in C++ through code generation or in Java by selecting the always/delta implementation at intialize time.

**Comment by ddebrunner** [comment]
Whatever approach is chosen I think the type `Notification`  needs to change its name as it's not a notification, it's just a representation of a metric and its value.

On the choice I prefer option 1, as the delta value is likely to be specific to individual metrics, e.g. a tuple count I may want updates every 100 tuples, but queuing metrics every change. One question is does it need to be an enum or could it be a boolean parameter, are there other likely modes?

**Comment by m-kotowski** [comment]
As mentioned in issue #13, I am open for every good replacement for `Notification`. What about `(Metric)Report` or `(Metric)Status`?

Regarding the boolean parameter: I am aware that many operators specify boolean parameters. But, even if I have no idea yet whether there are other likely modes, it is easier to extend an existing enum than to extend a boolean to a 3rd or 4th value.

After discussing with some colleagues following proposal:

* Introduce **emitMetricTuple** with the following values: *periodic* (instead of *always*), *onChangedValue*.
* Future extensions could be:
  * *onAbsoluteDeltaGreaterThan** mode with **delta** parameter
  * *onValueLessThanThreshold* mode with **threshold** parameter
  * *onValueGreaterThanThreshold* mode with **threshold** parameter
  * Specify thresholds, deltas, modes in the JSON-formatted filterDocument per metric. The parameter values could be interpreted as defaults for metrics without the additional settings

**Comment by m-kotowski** [comment]
@ddebrunner Any review comments for the pull request?

**Comment by ddebrunner** [comment]
Added some comments.

**Comment by m-kotowski** [comment]
Incorporated the proposed changes. Reopen if needed.
