### ISSUE TITLE
Change style of SPL types in toolkits.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.metrics#12]
The SPL types in this toolkit have the convention of ending with `_t`.
https://github.com/IBMStreams/streamsx.metrics/blob/master/com.ibm.streamsx.metrics/com.ibm.streamsx.metrics/Types.spl

That doesn't match the recommended style:
http://www.ibm.com/support/knowledgecenter/en/SSCRJU_4.0.0/com.ibm.streams.dev.doc/doc/str_nametype.html

or types in other toolkits.

For consistency within the toolkits and product can the types be changed to names like `Origin`, `Notification`.

**Comment by m-kotowski** [comment]
+1 : Will change it.
