### ISSUE TITLE
Have a consistent notification type?

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.metrics#13]
Just to note that the SPL standard toolkit already has a notification type for JMX, if `Notification_t` is a JMX notification then should it be consistent with the existing type.

_Mainly entered as a reminder to follow up with more investigation_

**Comment by m-kotowski** [comment]
The JMX notification is described [here](http://www.ibm.com/support/knowledgecenter/en/SSCRJU_4.2.0/com.ibm.streams.toolkits.doc/spldoc/dita/tk$spl/spl$spl.control$control.html#spldoc_compilationunit__type__MBeanNotification).

The `Notification_t` type is not a JMX notification but a notification about a (seen or changed) metric value. Therefore, I would stay with the specified type, which has attributes with names fitting to the JMX-returned domain/instance/job/operator/port/metric-relevant values, for example, lastTimeRetrieved.

Perhaps the name `Notification` can be improved? Any ideas? If not, please close this issue.
