### ISSUE TITLE
Add metric kind to Notification.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.metrics#15]
Metric kind is a key piece of information for a generic tool.

**Comment by m-kotowski** [comment]
+1

I will also add metricType, which can be, for example, "system" or "custom".

Metrics that are created with spl.utility::createCustomMetric(), return "unknown" as metric kind. Only system and operator metrics that are specified during compile-time, return counter, gauge, or time.

**Comment by m-kotowski** [comment]
This enhancement is available in the master branch. Reopen if needed.
