### ISSUE TITLE
Make MetricsSource relocatable.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.metrics#17]
https://github.com/IBMStreams/streamsx.metrics/blob/master/com.ibm.streamsx.metrics/impl/java/src/com/ibm/streamsx/metrics/MetricsSource.java#L57

Instead of effectively hard-coding the required jars load them dynamically. 

I'll provide a pull request.

**Comment by m-kotowski** [comment]
Is using the [@Libraries annotation](http://www.ibm.com/support/knowledgecenter/en/SSCRJU_4.2.0/com.ibm.streams.spl-java-operators.doc/api/com/ibm/streams/operator/model/Libraries.html) not the recommended way to do it?

If it is not recommended, the Knowledge Center should have a page under [Developing Java primitive operators](http://www.ibm.com/support/knowledgecenter/en/SSCRJU_4.2.0/com.ibm.streams.dev.doc/doc/javaprimitiveoperators.html) explaining pros/cons and showing an example.

**Comment by ddebrunner** [comment]
@Libraries is one mechanism for loading the jars (classes) for an operator. 

When using a relative path the jar is in the toolkit and any application that uses the operator will be relocatable, that is not depend on any hard-coded path from the compilation machine.

However if you put a absolute path in there or use an environment variable then the operator has dependency on a path that may not exist on a deployment machine, making any application that uses the operator not relocatable. That may be fine in some cases, e.g. on-premise installs where build, test and production systems have a set of know installs of required jars. However a general purpose toolkit should not be using a mechanism using creating hard-coded paths, since it's likely that the deployment system may not have a matching path, especially for Bluemix.

**Comment by m-kotowski** [comment]
Delivered with [this](https://github.com/IBMStreams/streamsx.metrics/commit/6b2684f5d15da10390fdb5a3078772dfdacf21ea) commit.
