### ISSUE TITLE
Reduce Streams product dependency.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.metrics#18]
Currently the toolkit is marked as requiring 4.2, it would be good to lower this to 4.0.1 or 4.1 for wider adoption.

**Comment by markheger** [comment]
Streams 4.0.1 is not possible as since a symbol error is raised:
    [javac]   symbol:   class DataException
    [javac]   location: package com.ibm.streams.operator

Change toolkit dependency to 4.1 after successful testing the sample.
