### ISSUE TITLE
MetricsSource supports application configuration

### ISSUE THREAD

**Issue by m-kotowski** [IBMStreams/streamsx.metrics#24]
Credentials or other application configuration can change during the lifetime of a job. Streams offers [application configuration objects](http://www.ibm.com/support/knowledgecenter/en/SSCRJU_4.2.0/com.ibm.streams.admin.doc/doc/creating-secure-app-configs.html) to store such information in Apache ZooKeeper in an encoded state.

The following MetricsSource parameters are candidates to be stored in application configuration objects:

* connectionURL: except that we find a solution to retrieve it automatically (see issue #5)
* password: passwords often change periodically and we do not want to restart or recompile apps
* filterDocument: instead of storing the configuration as JSON-encoded file, it might be useful to have the configuration centralized; we must be aware that different operators can have different configurations in the same application

Using application configuration objects stands in contrast to issue #18 because this feature is available since Streams v4.2 only.

**Comment by ddebrunner** [comment]
The iot toolkit supports application config and supports 4.1 or later, but just using the application configs from SPL.

Though technically it should be possible in Java to see if app configs exist, and if not don't use them.

**Comment by m-kotowski** [comment]
Following features will be implemented:

* Introduce the optional **applicationConfigurationName** parameter.
* Make the **connectionURL**, **user**, **password**, and **filterDocument** parameters optional from the operator's point of view.
* If the **applicationConfigurationName** parameter is not present, the **connectionURL**, **user**, **password**, and **filterDocument** parameters are mandatory.
* If the application configuration does not provide values for the **connectionURL**, **user**, **password**, and **filterDocument** and if the corresponding parameters are also not present, raise an exception.
* The application configuration is read during the startup phase only. The JMX error handling and dynamic updates of the filter document are not handled with this issue, but with issue #5.

**Comment by m-kotowski** [comment]
Delivered with the following commits: [commit 1](https://github.com/IBMStreams/streamsx.metrics/commit/4df1a71c474fa8bb9746e934084804532761bbd7), [commit 2](https://github.com/IBMStreams/streamsx.metrics/commit/77a9bde2c2b799ad3afb24087dfdc49a67d57dcd)
