### ISSUE TITLE
Need Getting Started instructions for toolkit

### ISSUE THREAD

**Issue by chanskw** [IBMStreams/streamsx.metrics#36]
I wanted to try out the toolkit to monitor my application.  When I tried to build by running ant, I got the following errors.

I am unsure how to get started with this toolkit.

[chanskw@chanskw1 streamsx.metrics]$ ant
Buildfile: /home/chanskw/git/streamsx.metrics/build.xml

toolkit:

init:
     [copy] Copying 1 file to /home/chanskw/git/streamsx.metrics/com.ibm.streamsx.metrics

compile:
    [javac] Compiling 38 source files to /home/chanskw/git/streamsx.metrics/com.ibm.streamsx.metrics/impl/java/build
    [javac] /home/chanskw/git/streamsx.metrics/com.ibm.streamsx.metrics/impl/java/src/com/ibm/streamsx/metrics/internal/Closeable.java:5: error: illegal start of type
    [javac] 	default void close() throws Exception {
    [javac] 	^
    [javac] /home/chanskw/git/streamsx.metrics/com.ibm.streamsx.metrics/impl/java/src/com/ibm/streamsx/metrics/internal/Closeable.java:5: error: = expected
    [javac] 	default void close() throws Exception {
    [javac] 	        ^
    [javac] /home/chanskw/git/streamsx.metrics/com.ibm.streamsx.metrics/impl/java/src/com/ibm/streamsx/metrics/internal/Closeable.java:5: error: ';' expected
    [javac] 	default void close() throws Exception {
    [javac] 	            ^
    [javac] /home/chanskw/git/streamsx.metrics/com.ibm.streamsx.metrics/impl/java/src/com/ibm/streamsx/metrics/internal/Closeable.java:5: error: illegal start of type
    [javac] 	default void close() throws Exception {
    [javac] 	                  ^
    [javac] /home/chanskw/git/streamsx.metrics/com.ibm.streamsx.metrics/impl/java/src/com/ibm/streamsx/metrics/internal/Closeable.java:5: error: <identifier> expected
    [javac] 	default void close() throws Exception {
    [javac] 	                   ^
    [javac] /home/chanskw/git/streamsx.metrics/com.ibm.streamsx.metrics/impl/java/src/com/ibm/streamsx/metrics/internal/Closeable.java:5: error: = expected
    [javac] 	default void close() throws Exception {
    [javac] 	                     ^
    [javac] /home/chanskw/git/streamsx.metrics/com.ibm.streamsx.metrics/impl/java/src/com/ibm/streamsx/metrics/internal/Closeable.java:5: error: ';' expected
    [javac] 	default void close() throws Exception {
    [javac] 	                           ^
    [javac] /home/chanskw/git/streamsx.metrics/com.ibm.streamsx.metrics/impl/java/src/com/ibm/streamsx/metrics/internal/Closeable.java:5: error: illegal start of type
    [javac] 	default void close() throws Exception {
    [javac] 	                                      ^
    [javac] /home/chanskw/git/streamsx.metrics/com.ibm.streamsx.metrics/impl/java/src/com/ibm/streamsx/metrics/internal/Closeable.java:5: error: <identifier> expected
    [javac] 	default void close() throws Exception {
    [javac] 	                                       ^
    [javac] /home/chanskw/git/streamsx.metrics/com.ibm.streamsx.metrics/impl/java/src/com/ibm/streamsx/metrics/internal/Closeable.java:7: error: = expected
    [javac] }
    [javac] ^
    [javac] /home/chanskw/git/streamsx.metrics/com.ibm.streamsx.metrics/impl/java/src/com/ibm/streamsx/metrics/internal/Closeable.java:7: error: reached end of file while parsing
    [javac] }
    [javac]  ^
    [javac] /home/chanskw/git/streamsx.metrics/com.ibm.streamsx.metrics/impl/java/src/com/ibm/streamsx/metrics/internal/Closeable.java:8: error: reached end of file while parsing
    [javac] 12 errors

BUILD FAILED
/home/chanskw/git/streamsx.metrics/build.xml:28: The following error occurred while executing this line:
/home/chanskw/git/streamsx.metrics/com.ibm.streamsx.metrics/build.xml:44: Compile failed; see the compiler error output for details.

Total time: 1 second

**Comment by markheger** [comment]
Java 1.8 is required.

**Comment by chanskw** [comment]
I only java 8 installed... or is this a problem with your build script that you need to adjust the java level?

**Comment by markheger** [comment]
Could you please show me your Java environment according to the error above?
`which javac`
`javac -version`
Have you had a look on latest BUILD.md and have you tried to build the toolkit with latest version?

**Comment by chanskw** [comment]
I did not even know BUILD.md exist... :)  I think this is why I suggested that we need some getting started documentation for someone like me (with no prior knowledge of the toolkit) to be able to get started and know where to look for information.

I haven't had a chance to retry .. but will do that next week.  Thanks!

**Comment by markheger** [comment]
https://github.com/IBMStreams/streamsx.metrics/wiki/Getting-Started
