### ISSUE TITLE
Create user friendly iopages.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.metrics#39]

**Comment by markheger** [comment]
Is there any template or recommendation described anywhere, e.g shall it look like streamsx.datetime?

**Comment by markheger** [comment]
I updated the iopages based on the template of messaging toolkit.
https://ibmstreams.github.io/streamsx.metrics/

**Comment by ddebrunner** [comment]
it needs to be linked in the top-level description like other projects.

**Comment by markheger** [comment]
@chanskw Could you please add the link to the top-level description. I have no permission for that.

**Comment by chanskw** [comment]
done
