### ISSUE TITLE
Change structure of the JSON filter document (filterDocument parameter)

### ISSUE THREAD

**Issue by m-kotowski** [IBMStreams/streamsx.metrics#4]
The current implementation uses a quite simple JSON format to specify the filters for domain, instance, job, operator, and metric names.

Excerpt from the checked-in filters.json file:
```
[
	{
		"domainNames":"domain[0-9.]+",
		"instanceNames":"instance[0-9.]+",
		"jobNames":"\\S+",
		"operatorNames":".*",
		"metricNames":"nWindowPunctsSubmitted",
	},
	{
		"domainNames":"domain\\S+",
		"instanceNames":
		[
			"instance4\\.2\\.0\\.0",
			"instance4\\.2\\.0\\.1",
			"streams4\\.2\\.0\\.0",
		],
		"jobNames":".*",
		"operatorNames":"\\S+",
		"metricNames":
		[
			"nTuplesSubmitted",
			"nWindowPunctsQueued",
			"nTuplesProcessed",
		]
	},
```

The filter document contains a list of tuples. Each tuple (currently) 5 attributes: domainNames, instanceNames, jobNames, operatorNames, and metricNames.

Each attribute can be a single string value, or a list of string values. The string values are regular expressions. An instance is monitored if its instance name matches at least one of the specified filters. For an instances, this means that the domain and the instance name (of the same filter tuple) must match.

With the introduction of port metrics (and in future perhaps also PE and PE connection metrics), a restructured filter document might be useful.

The proposal is to use the same contained-relation as it exists in Streams. This means, domains have instances, instances have jobs, jobs have operators, etc. This tree-like structure allows adding new elements on every level. The following JSON string shall sketch this idea:
```
[
	{
		domainNames:["a","b"]
		instances:
		[
			{
				instanceNames:["a","b"]
				jobs:
				[
					{
						jobNames:["x","y"]
						operators:
						[
							{
								operatorNames:["a","s","d"]
								metrics:[nPuncts,nSent,rnd]
								(input|output)Ports: # optional
								[
									{
										index:[1,2,3]
										metrics:["a","b","c"]
									}
								]
							},
							...
						],
					},
				]
			}
		]
	},
	{
		...
	},
]
```

The idea is to have a structure that can easily parsed and allows extensions without the need to rework the whole operator.

**Comment by m-kotowski** [comment]
As discussed in issue #19, the key names should be changed, too:

- domainIdPatterns
- instanceIdPatterns
- jobNamePatterns
- operatorNamePatterns
- etc.

**Comment by ddebrunner** [comment]
Does `metrics` support patterns? if not should it?

**Comment by ddebrunner** [comment]
The job config overlay added in Streams 4.2 also supports the concepts of operator matching via a pattern, should this toolkit use the same approach, so that we don't have two different ways to match all operators in the composite `KCC` (for example). No idea if they are different, or this is a superset of what job-config can do, but some investigation here to try to ensure a "single look and feel" across Streams would be good. ( @chanskw FYI - thoughts on trying to align this format in some way with job config overlay ?)

**Comment by m-kotowski** [comment]
The job configuration overlay is described [here](http://www.ibm.com/support/knowledgecenter/en/SSCRJU_4.2.0/com.ibm.streams.admin.doc/doc/job_configuration_overlays.html), and its parameter reference [here](http://www.ibm.com/support/knowledgecenter/en/SSCRJU_4.2.0/com.ibm.streams.ref.doc/doc/submitjobparameters.html).

Regarding the patterns, the reference says:
```
Specification of a name of an existing operator instance in the application after
UDP transformations. The name might contain zero or more '*' characters in the
specification. The '*' represents 0 or more occurrences of any legal name character.
For example, "Main.*.MyComp2.Filter[*]"
'[ ]' are normal characters, and do not have any regular expression meaning.*
```

This is a different syntax than the Java [Pattern](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html), which is used in the MetricsSource operator.

Do you know a Java API, which supports the simpler regex syntax and is part of a Streams installation? If not, I would prefer to go with the standard Java patterns.

**Comment by m-kotowski** [comment]
If needed, reopen.
